### ISSUE TITLE
[2017] Create sponsorship tiers

### ISSUE THREAD

**Issue by cobusbernard** [DevOpsCapeTown/devopsdays-web#3]
Need to add the sponsorship tiers.

**Comment by adrianmoisey** [comment]
Done: https://github.com/devopsdays/devopsdays-web/blob/4888f8b43edf8de74a8fb8fa6e3ebc000f251ff7/data/events/2017-cape-town.yml#L60-L72

**Comment by adrianmoisey** [comment]
https://github.com/devopsdays/devopsdays-web/pull/1650

**Comment by cobusbernard** [comment]
Thanks!
